version: 2
jobs:
  build:
    docker:
      - image: node:12.8.0-alpine

    steps:
      - run: apk add ca-certificates

      - checkout

      - restore_cache:
          keys:
            - node-modules-{{ checksum "package.json" }}
            - node-modules-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: node-modules-{{ checksum "package.json" }}

      - run: npm run analyse && npm run test
