version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    default_reviewers:
    - "thenativeweb/wolkenkit-dev"
    default_assignees:
    - "goloroden"
    - "yeldiRium"
    default_labels:
    - "Dependencies"
    allowed_updates:
    - match:
        update_type: "security"
    version_requirement_updates: "increase_versions"
