name: Release

on:
  push:
    branches:
      - 'master'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: |
        npm install
    - name: Run code analysis
      run: |
        npm run analyse
    - name: Run tests
      run: |
        npm run test
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN_ADMIN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN_ADMIN }}
      run: npx semantic-release
